package com.jianma.designyl.model;
// Generated 2017-5-9 16:09:09 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Production generated by hbm2java
 */
@Entity
@Table(name = "production", catalog = "design_yl")
public class Production implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	private int userId;
	private String content;
	private String attachFile;
	private byte fileType;
	private String videoAddress;
	private String h5Address;
	private Date createTime;
	private Float score;
	private Byte status; //1.宸叉彁浜ゃ��2.瀹℃牳鏈�氳繃銆�3.瀹℃牳宸查�氳繃銆�4.鍒濋�夊叆鍥淬��5.鍒濋�夋湭鍏ュ洿銆�6.澶嶉�夊叆鍥淬��7澶嶉�夋湭鍏ュ洿
	private String pimage;
	private byte participantType; //鍙傝禌浜哄憳绫诲瀷 1锛氫釜浜猴紝 2锛氬洟闃燂紝 3锛氬叕鍙�
	private String participantName; //鍙傝禌浜哄憳鍚嶇О銆佸洟闃熷悕绉般�佸叕鍙稿悕绉�
	private String participantIdNumber; //鍙傝禌浜哄憳韬唤璇佸彿鐮併�佽惀涓氭墽鐓у彿鐮�
	private String participantBrief; //绠�浠�
	private String teamMember; //鍥㈤槦鎴愬憳
	private String affiliatedUnit;
	private byte round;
	private String weblink;
	
	public Production() {
	}

	public Production(String title, int userId, String content,String attachFile,byte participantType,
			String participantName, String participantIdNumber, String teamMember, Date createTime) {
		this.title = title;
		this.userId = userId;
		this.content = content;
		this.participantType = participantType;
		this.participantName = participantName;
		this.participantIdNumber = participantIdNumber;
		this.teamMember = teamMember;
		this.createTime = createTime;
		this.attachFile = attachFile;
	}

	public Production(String title, int userId, byte fileType, String pimage, String content,String attachFile,
			String videoAddress, String h5Address,Byte status,byte participantType, String participantName,
			String participantIdNumber, String participantBrief, String teamMember, Float score,
			Date createTime) {
		this.title = title;
		this.userId = userId;
		this.fileType = fileType;
		this.pimage = pimage;
		this.content = content;
		this.videoAddress = videoAddress;
		this.h5Address = h5Address;
		this.status = status;
		this.participantType = participantType;
		this.participantName = participantName;
		this.participantIdNumber = participantIdNumber;
		this.participantBrief = participantBrief;
		this.teamMember = teamMember;
		this.score = score;
		this.createTime = createTime;
		this.attachFile = attachFile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 30)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}


	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	@Column(name = "attach_file", length = 100)
	public void setContent(String content) {
		this.content = content;
	}

	public String getAttachFile() {
		return attachFile;
	}

	public void setAttachFile(String attachFile) {
		this.attachFile = attachFile;
	}

	@Column(name = "fileType")
	public byte getFileType() {
		return fileType;
	}

	public void setFileType(byte fileType) {
		this.fileType = fileType;
	}

	@Column(name = "videoAddress")
	public String getVideoAddress() {
		return videoAddress;
	}

	public void setVideoAddress(String videoAddress) {
		this.videoAddress = videoAddress;
	}

	@Column(name = "h5Address")
	public String getH5Address() {
		return h5Address;
	}

	public void setH5Address(String h5Address) {
		this.h5Address = h5Address;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}
	
	@Column(name = "pImage")
	public String getPimage() {
		return this.pimage;
	}

	public void setPimage(String pimage) {
		this.pimage = pimage;
	}
	
	@JsonFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	@Column(name = "score", precision = 5)
	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}
	
	@Column(name = "participant_type", nullable = false)
	public byte getParticipantType() {
		return this.participantType;
	}

	public void setParticipantType(byte participantType) {
		this.participantType = participantType;
	}

	@Column(name = "participant_name", nullable = false, length = 20)
	public String getParticipantName() {
		return this.participantName;
	}

	public void setParticipantName(String participantName) {
		this.participantName = participantName;
	}

	@Column(name = "participant_id_number", nullable = false, length = 25)
	public String getParticipantIdNumber() {
		return this.participantIdNumber;
	}

	public void setParticipantIdNumber(String participantIdNumber) {
		this.participantIdNumber = participantIdNumber;
	}

	@Column(name = "participant_brief")
	public String getParticipantBrief() {
		return this.participantBrief;
	}

	public void setParticipantBrief(String participantBrief) {
		this.participantBrief = participantBrief;
	}

	@Column(name = "team_member", length = 30)
	public String getTeamMember() {
		return this.teamMember;
	}

	public void setTeamMember(String teamMember) {
		this.teamMember = teamMember;
	}

	@Column(name = "round")
	public byte getRound() {
		return this.round;
	}

	public void setRound(byte round) {
		this.round = round;
	}
	
	@Column(name = "affiliatedUnit", length = 20)
	public String getAffiliatedUnit() {
		return this.affiliatedUnit;
	}

	public void setAffiliatedUnit(String affiliatedUnit) {
		this.affiliatedUnit = affiliatedUnit;
	}

	@Column(name = "weblink", length = 255)
	public String getWeblink() {
		return weblink;
	}

	public void setWeblink(String weblink) {
		this.weblink = weblink;
	}
	
}
